// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVDvS8kICDCnN1I5UtPrx7LvEAqsIrzF8',
    appId: '1:1094088247186:web:b10672bba9d19836cfa34b',
    messagingSenderId: '1094088247186',
    projectId: 'health-pet-7b1e0',
    authDomain: 'health-pet-7b1e0.firebaseapp.com',
    storageBucket: 'health-pet-7b1e0.firebasestorage.app',
    measurementId: 'G-VC2K7ZFXBG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVq0ESq6wGwyxPq2NsdebFk4r-CstXSpw',
    appId: '1:1094088247186:android:f492c5cf39351c96cfa34b',
    messagingSenderId: '1094088247186',
    projectId: 'health-pet-7b1e0',
    storageBucket: 'health-pet-7b1e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjVmpRx5iLIGot2seMR4bSUysNCmDApTU',
    appId: '1:1094088247186:ios:30d745d63d2511c0cfa34b',
    messagingSenderId: '1094088247186',
    projectId: 'health-pet-7b1e0',
    storageBucket: 'health-pet-7b1e0.firebasestorage.app',
    iosBundleId: 'com.example.healthPet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjVmpRx5iLIGot2seMR4bSUysNCmDApTU',
    appId: '1:1094088247186:ios:30d745d63d2511c0cfa34b',
    messagingSenderId: '1094088247186',
    projectId: 'health-pet-7b1e0',
    storageBucket: 'health-pet-7b1e0.firebasestorage.app',
    iosBundleId: 'com.example.healthPet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVDvS8kICDCnN1I5UtPrx7LvEAqsIrzF8',
    appId: '1:1094088247186:web:e766e85de0949144cfa34b',
    messagingSenderId: '1094088247186',
    projectId: 'health-pet-7b1e0',
    authDomain: 'health-pet-7b1e0.firebaseapp.com',
    storageBucket: 'health-pet-7b1e0.firebasestorage.app',
    measurementId: 'G-26FPQCPEDX',
  );
}
